spring:
  application:
    name: container-with-jib
  cloud:
    kubernetes:
      secrets:
        name: container-with-jib-secret
        namespace: container-with-jib
        sources:
          - name: server_port
          - name: value
      reload: # This is the section for dynamic reloading
        enabled: true
        mode: polling # Or 'event' if you set up the webhook
        period: 5000 # Polling interval in milliseconds (e.g., 5 seconds)
        strategy: refresh # Or 'restart_context', 'shutdown'
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.context.refresh: DEBUG # For refresh scope events
management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always
      access: unrestricted
    prometheus:
      access: unrestricted
server:
  port: ${SERVER_PORT:8009}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024


resilience4j:
  circuitbreaker:
    instances:
      Test:
        minimum-number-of-calls: 4
        sliding-window-size: 8
