spring:
  application:
    name: container-with-jib
  config:
    import: optional:configtree:/app/secrets/
  cloud:
    kubernetes:
      secrets:
        enabled: true
        paths: /app/secrets/
      reload: # This is the section for dynamic reloading
        enabled: true
        mode: event
        monitoring-secrets: true
        strategy: refresh

#value: ${file:value}
#my:
#  secret:
#    server-port: ${file:/app/resources/secrets/server_port}
#    value: "file:/src/main/resources/secrets/value"
##    value: ${file:/app/resources/secrets/value}

logging:
  level:
    org.springframework.cloud.health.RefreshScopeHealthIndicator: DEBUG
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.kubernetes.client: DEBUG
    org.springframework.cloud.kubernetes.client.config: DEBUG
    org.springframework.cloud.kubernetes.client.secrets: DEBUG
management:
  health:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "refresh, health, prometheus, restart"
    access:
      default: unrestricted
  endpoint:
    restart:
      access: unrestricted
    refresh:
      access: unrestricted
    health:
      show-details: always
      access: unrestricted
      probes:
        enabled: true
    prometheus:
      access: unrestricted
    resume:
      enabled: true
server:
  port: ${server_port:80}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024


resilience4j:
  circuitbreaker:
    instances:
      Test:
        minimum-number-of-calls: 4
        sliding-window-size: 8
