spring:
  application:
    name: container-with-jib
  cloud:
    kubernetes:
      config:
        enabled: true
        paths: /etc/config
      secrets:
        namespace: container-with-jib
        enabled: true
#        sources:
#          - name: container-with-jib-secret
        paths: /etc/config
      reload: # This is the section for dynamic reloading
        enabled: true
        mode: polling
        monitoring-secrets: true
        namespaces: container-with-jib
        period: 5000ms
        strategy: refresh

value: /etc/config/value

logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.kubernetes.client: DEBUG
    org.springframework.cloud.kubernetes.client.config: DEBUG
    org.springframework.cloud.kubernetes.client.secrets: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "refresh, health, prometheus, restart"
    access:
      default: unrestricted
  endpoint:
    restart:
      access: unrestricted
    refresh:
      access: unrestricted
    health:
      show-details: always
      access: unrestricted
      probes:
        enabled: true
    prometheus:
      access: unrestricted
    resume:
      enabled: true
server:
  port: ${server_port:80}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024


resilience4j:
  circuitbreaker:
    instances:
      Test:
        minimum-number-of-calls: 4
        sliding-window-size: 8
