spring:
  application:
    name: container-with-jib
  cloud:
    kubernetes:
      config:
        enabled: false
      secrets:
        namespace: container-with-jib
        enabled: true
        sources:
          - name: container-with-jib-secret
      reload: # This is the section for dynamic reloading
        enabled: true
        strategy: refresh
#value: ${VALUE}
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.context.refresh: DEBUG # For refresh scope events
management:
  endpoints:
    web:
      exposure:
        include: "refresh, health, prometheus"
    access:
      default: unrestricted
  endpoint:
    refresh:
      access: unrestricted
    health:
      show-details: always
      access: unrestricted
    prometheus:
      access: unrestricted
server:
  port: ${server_port:80}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024


resilience4j:
  circuitbreaker:
    instances:
      Test:
        minimum-number-of-calls: 4
        sliding-window-size: 8
